// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OwnStream.Database;

#nullable disable

namespace OwnStream.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260711112544_AddSizesToVideos")]
    partial class AddSizesToVideos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OwnStream.Database.Models.DatabaseContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Dictionary<string, string>>("AgeRatings")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Backdrop")
                        .HasColumnType("text");

                    b.Property<string>("Banner")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("FinishedStreamingAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LibraryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Logo")
                        .HasColumnType("text");

                    b.Property<string>("Poster")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ReleasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tagline")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Dictionary<string, string>>("TranslatedDescription")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Dictionary<string, string>>("TranslatedTagline")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Dictionary<string, string>>("TranslatedTitle")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LibraryId");

                    b.ToTable("Content");
                });

            modelBuilder.Entity("OwnStream.Database.Models.DatabaseContentExternalId", b =>
                {
                    b.Property<Guid>("ContentId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProviderId")
                        .HasColumnType("text");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ContentId", "ProviderId");

                    b.HasIndex("ProviderId", "ExternalId");

                    b.ToTable("ContentExternalIds");
                });

            modelBuilder.Entity("OwnStream.Database.Models.DatabaseEpisode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Episode")
                        .HasColumnType("integer");

                    b.Property<Guid>("ParentContentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ReleasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Season")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Dictionary<string, string>>("TranslatedSummary")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Dictionary<string, string>>("TranslatedTitle")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParentContentId");

                    b.ToTable("Episode");
                });

            modelBuilder.Entity("OwnStream.Database.Models.DatabaseFfmpegJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Arguments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InputPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<string>("OutputPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Progress")
                        .HasColumnType("integer");

                    b.Property<int?>("ProgressMax")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RelevantContentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RelevantEpisodeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RelevantLibraryId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RelevantVideoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RelevantWebhookId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RelevantContentId");

                    b.HasIndex("RelevantEpisodeId");

                    b.HasIndex("RelevantLibraryId");

                    b.HasIndex("RelevantVideoId");

                    b.HasIndex("RelevantWebhookId");

                    b.ToTable("FfmpegJobs");
                });

            modelBuilder.Entity("OwnStream.Database.Models.DatabaseInputLibrary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TranscodeLibraryId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TranscodeLibraryId");

                    b.ToTable("InputLibraries");
                });

            modelBuilder.Entity("OwnStream.Database.Models.DatabaseLibrary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Libraries");
                });

            modelBuilder.Entity("OwnStream.Database.Models.DatabaseUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("Permissions")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Username" }, "User_Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OwnStream.Database.Models.DatabaseVideo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("EncodingSettings")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid?>("EpisodeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Fps")
                        .HasColumnType("integer");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Length")
                        .HasColumnType("integer");

                    b.Property<Guid>("LibraryId")
                        .HasColumnType("uuid");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("LibraryId");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("OwnStream.Database.Models.DatabaseVideoSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("EndMilliseconds")
                        .HasColumnType("integer");

                    b.Property<int>("StartMilliseconds")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("VideoDuration")
                        .HasColumnType("integer");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VideoId");

                    b.ToTable("VideoSegments");
                });

            modelBuilder.Entity("OwnStream.Database.Models.DatabaseWatchProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ContentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EpisodeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("FullyWatched")
                        .HasColumnType("boolean");

                    b.Property<int>("MillisecondsWatched")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid");

                    b.Property<int>("VideoLength")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContentId");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("UserId");

                    b.HasIndex("VideoId");

                    b.ToTable("WatchProgress");
                });

            modelBuilder.Entity("OwnStream.Database.Models.DatabaseWebhook", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Authentication")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("DeleteOnConvert")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LibraryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LibraryId");

                    b.ToTable("Webhooks");
                });

            modelBuilder.Entity("OwnStream.Database.Models.DatabaseContent", b =>
                {
                    b.HasOne("OwnStream.Database.Models.DatabaseLibrary", "Library")
                        .WithMany()
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Library");
                });

            modelBuilder.Entity("OwnStream.Database.Models.DatabaseContentExternalId", b =>
                {
                    b.HasOne("OwnStream.Database.Models.DatabaseContent", "Content")
                        .WithMany("ExternalIds")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Content");
                });

            modelBuilder.Entity("OwnStream.Database.Models.DatabaseEpisode", b =>
                {
                    b.HasOne("OwnStream.Database.Models.DatabaseContent", "ParentContent")
                        .WithMany("Episodes")
                        .HasForeignKey("ParentContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentContent");
                });

            modelBuilder.Entity("OwnStream.Database.Models.DatabaseFfmpegJob", b =>
                {
                    b.HasOne("OwnStream.Database.Models.DatabaseContent", "RelevantContent")
                        .WithMany()
                        .HasForeignKey("RelevantContentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OwnStream.Database.Models.DatabaseEpisode", "RelevantEpisode")
                        .WithMany()
                        .HasForeignKey("RelevantEpisodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OwnStream.Database.Models.DatabaseLibrary", "RelevantLibrary")
                        .WithMany()
                        .HasForeignKey("RelevantLibraryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OwnStream.Database.Models.DatabaseVideo", "RelevantVideo")
                        .WithMany()
                        .HasForeignKey("RelevantVideoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OwnStream.Database.Models.DatabaseWebhook", "RelevantWebhook")
                        .WithMany()
                        .HasForeignKey("RelevantWebhookId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("RelevantContent");

                    b.Navigation("RelevantEpisode");

                    b.Navigation("RelevantLibrary");

                    b.Navigation("RelevantVideo");

                    b.Navigation("RelevantWebhook");
                });

            modelBuilder.Entity("OwnStream.Database.Models.DatabaseInputLibrary", b =>
                {
                    b.HasOne("OwnStream.Database.Models.DatabaseLibrary", "TranscodeLibrary")
                        .WithMany()
                        .HasForeignKey("TranscodeLibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TranscodeLibrary");
                });

            modelBuilder.Entity("OwnStream.Database.Models.DatabaseVideo", b =>
                {
                    b.HasOne("OwnStream.Database.Models.DatabaseEpisode", "Episode")
                        .WithMany("Videos")
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OwnStream.Database.Models.DatabaseLibrary", "Library")
                        .WithMany()
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Episode");

                    b.Navigation("Library");
                });

            modelBuilder.Entity("OwnStream.Database.Models.DatabaseVideoSegment", b =>
                {
                    b.HasOne("OwnStream.Database.Models.DatabaseVideo", "Video")
                        .WithMany("VideoSegments")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Video");
                });

            modelBuilder.Entity("OwnStream.Database.Models.DatabaseWatchProgress", b =>
                {
                    b.HasOne("OwnStream.Database.Models.DatabaseContent", "Content")
                        .WithMany("WatchProgresses")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("OwnStream.Database.Models.DatabaseEpisode", "Episode")
                        .WithMany("WatchProgresses")
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("OwnStream.Database.Models.DatabaseUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OwnStream.Database.Models.DatabaseVideo", "Video")
                        .WithMany("WatchProgresses")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Content");

                    b.Navigation("Episode");

                    b.Navigation("User");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("OwnStream.Database.Models.DatabaseWebhook", b =>
                {
                    b.HasOne("OwnStream.Database.Models.DatabaseLibrary", "Library")
                        .WithMany("Webhooks")
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Library");
                });

            modelBuilder.Entity("OwnStream.Database.Models.DatabaseContent", b =>
                {
                    b.Navigation("Episodes");

                    b.Navigation("ExternalIds");

                    b.Navigation("WatchProgresses");
                });

            modelBuilder.Entity("OwnStream.Database.Models.DatabaseEpisode", b =>
                {
                    b.Navigation("Videos");

                    b.Navigation("WatchProgresses");
                });

            modelBuilder.Entity("OwnStream.Database.Models.DatabaseLibrary", b =>
                {
                    b.Navigation("Webhooks");
                });

            modelBuilder.Entity("OwnStream.Database.Models.DatabaseVideo", b =>
                {
                    b.Navigation("VideoSegments");

                    b.Navigation("WatchProgresses");
                });
#pragma warning restore 612, 618
        }
    }
}
