using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Cors;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OwnStream.ApiModels.Response;
using OwnStream.Database;
using OwnStream.Database.Models;

namespace OwnStream.Controllers.Api;

[ApiController, Route("/api/search"), Authorize, EnableCors("Api")]
public class SearchController(DatabaseContext db) : Controller
{
	[HttpGet("")]
	public SearchResponse Search([FromQuery] string? q, [FromQuery] string type = "all", [FromQuery] int offset = 0,
		[FromQuery] int limit = 20, [FromQuery] Guid? libraryId = null)
	{
		// TODO: Add facets? For example: externalid:imdb:tt6741278, cast:"J.K. Simmons", network:AMC, genre:Comedy
		//       And autogenerated tags:
		//       hastag:custom-tag, hastag:hassub:eng, -hastag:hasdub:eng
		if (string.IsNullOrWhiteSpace(q))
			return new SearchResponse
			{
				Results = [],
				Total = 0,
				HasMore = false
			};

		if (type is not ("all" or "content" or "episode" or "movie" or "tv"))
			type = "all";

		DatabaseLibrary? library = db.Libraries.Find(libraryId ?? Guid.Empty);
		Guid? normalizedLibraryId = library?.Id;

		offset = Math.Max(0, offset);
		limit = Math.Clamp(limit, 1, 100);

		string query = q.Trim();
		string pattern = $"%{query}%";

		SearchResult[] contentResults =
			type is "all" or "content" or "tv" or "movie"
				? db.Content
					.Where(x =>
						EF.Functions.ILike(x.Title, pattern) ||
						EF.Functions.ILike(x.Tagline, pattern) ||
						EF.Functions.ILike(x.Description, pattern))
					.Where(x => type == "all" ||
					            type == "content" ||
					            type == "movie" && x.Type == DatabaseContent.ContentType.Movie ||
					            type == "tv" && x.Type == DatabaseContent.ContentType.Tv)
					.Where(x => normalizedLibraryId == null || x.LibraryId == normalizedLibraryId)
					.Select(x => new SearchResult
					{
						Kind = "content",
						Id = x.Id,
						Title = x.Title,
						TranslatedTitle = x.TranslatedTitle.GetLocalized(x.Title, HttpContext),
						Description = x.Description,
						TranslatedDescription = x.TranslatedDescription.GetLocalized(x.Description, HttpContext),
						Images = new Content.ContentImages(x)
					})
					.ToArray()
				: [];

		SearchResult[] episodeResults =
			type is "all" or "episode"
				? db.Episode
					.Include(x => x.ParentContent)
					.Where(x => x.ParentContent.Type == DatabaseContent.ContentType.Tv)
					.Where(x =>
						EF.Functions.ILike(x.Title, pattern) ||
						EF.Functions.ILike(x.Summary, pattern) ||
						EF.Functions.ILike(x.ParentContent.Title, pattern))
					.Where(x => normalizedLibraryId == null || x.ParentContent.LibraryId == normalizedLibraryId)
					.OrderBy(x => x.Season)
					.ThenBy(x => x.Episode)
					.Select(x => new SearchResult
					{
						Kind = "episode",
						Id = x.Id,
						ContentId = x.ParentContentId,
						ContentTitle = x.ParentContent.Title,
						Title = x.Title,
						TranslatedTitle = x.TranslatedTitle.GetLocalized(x.Title, HttpContext),
						Description = x.Summary,
						TranslatedDescription = x.TranslatedSummary.GetLocalized(x.Summary, HttpContext),
						Images = new Content.ContentImages(x, x.ParentContent),
						Season = x.Season,
						Episode = x.Episode
					})
					.ToArray()
				: [];

		SearchResult[] results = contentResults
			.Concat(episodeResults)
			.Skip(offset)
			.Take(limit)
			.ToArray();

		int total = contentResults.Length + episodeResults.Length;

		return new SearchResponse
		{
			Results = results,
			Total = total,
			HasMore = offset + results.Length < total
		};
	}
}